### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by drmetro09** [Feramance/qBitrr#169]
Qbitrr isnt working like it used to before multiple errors , api fails etc 
Its very versatile tool but something is failing 
Second problem is with the temp profile switching, the profiles are not switching on its own even after waiting for hours , they switch only when qbitrr docker container is restarted.
Image attached for reference 

![Image](https://github.com/user-attachments/assets/ac47ab6a-5cd8-4098-b910-5e5412811170)

**Comment by Feramance** [comment]
Hi @drmetro09 

Can you send logs, config and what version of qbittorrent are you using?

**Comment by drmetro09** [comment]
Hi ,i was trying the pr-170 the webui doesnt load sonarr and the temporary profile switching is not showing in webui

**Comment by drmetro09** [comment]
Hi , i mapped the container port 6969 to host port 5094 and also config.toml i put the new points you introduced here on github still the webui is not opening when i go to 5094 port

**Comment by Feramance** [comment]
Can you send me your config and docker compose?

**Comment by drmetro09** [comment]
![Image](https://github.com/user-attachments/assets/ef15f681-7cd8-487e-9308-3a4df8a3bc5c)

Doesn’t show the list in sonarr as well as radarr

**Comment by Feramance** [comment]
Noticed issues that didn't show up in testing with 5.1.0 myself too, hotfix incoming this morning

**Comment by Feramance** [comment]
Fixed in 5.1.1

**Comment by drmetro09** [comment]
The radarr and sonarr not showing the list is still a problem

**Comment by drmetro09** [comment]
![Image](https://github.com/user-attachments/assets/32ecbe4b-ac2e-4200-a8dc-e344721d9ec1)

Same problem persists, tried clearing cache and also checked on other browser

**Comment by Feramance** [comment]
Try pr-188 please and let me know if it fixes things for you

**Comment by drmetro09** [comment]
Is it supposed to show only the movies which are monitored in radarr or all the movies in radarr regardless whether monitored or not ?

**Comment by drmetro09** [comment]
Than its fixed ! Because now it shows the monitored ones

**Comment by drmetro09** [comment]
Request:  show all logs in webui instead of selecting one by one to see
